Resolve issue with deriving `Counter CounterM`
Deriving `Counter CounterM` using `deriving via` in the example failed
when implemented as follows.

```
newtype CounterM a = CounterM (State Int a)
  deriving (Functor, Applicative, Monad)
  deriving Counter via TheCounterState (State (TheValue Int))
```

The compiler error read:

```
src/Example/CountLog.hs:106:12: error:
    * Couldn't match type `Int' with `TheValue Int'
        arising from the coercion of the method `count'
          from type `TheCounterState (State (TheValue Int)) Int'
            to type `CounterM Int'
    * When deriving the instance for (Counter CounterM)
    |
106 |   deriving Counter via TheCounterState (State (TheValue Int))
    |            ^^^^^^^
```

Instead, `CounterM` had to be explicitly defined as a state monad over
`TheValue Int`.

```
newtype CounterM a = CounterM (State (TheValue Int) a)
```

As it turns out, the issue is resolved by importing `StateT` and it's
constructor.